version: '3'
services:
  nodejs-server:
    build:
      context: ./goat-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: node-api
    volumes:
       - ./goat-api:/usr/src/app/goat-api
       - /usr/src/app/goat-api/node_modules
    links:
       - mysql
  vue-ui:
    build:
      context: ./goat
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./goat:/usr/src/app/goat
       - /usr/src/app/goat/node_modules
  mysql:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    container_name: mysql-ui
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: goat